- source/includes/options-mongosqld.yaml
Added information that BI Connector supports the readPreference ande readPreferenceTags options in the --mongo-uri option. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-9244/reference/mongosqld.html#cmdoption--mongo-uri)
> (DOCS-9244): Added read preference mongo-uri options.

- source/reference/mongosqld.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-855/reference/mongosqld.html#net.bindIp
> DOCSP-855 - Added note about binding to multiple IP addresses.

- source/includes/options-mongodrdl.yaml
- source/includes/options-shared.yaml
- source/reference/mongodrdl.txt
- source/tutorial/connecting.txt
@rkumar-mongo : This removes Kerberos from the BI Connector documentation. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-10434/tutorial/connecting.html)
> (DOCS-10434): Removed mention of Kerberos throughout documentation.

- source/includes/facts/tableau-restart.rst
- source/includes/list-tables/tableau-default-tdc-locations.rst
- source/includes/steps-connect-tableau-authentication-tdc.yaml
- source/includes/steps-connect-tableau-mongosql-plugin.yaml
- source/includes/tableau-default-tdc-locations.rst
- source/includes/tdc/mongodb-mac.tdc
- source/includes/tdc/mongodb-ssl.tdc
- source/includes/tdc/mongodb-win.tdc
- source/tutorial/connecting.txt
@steveren : I updated the Tableau section with all of the appropriate information. It is [staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-970/tutorial/connecting.html#connect-with-tableau).
> (DOCSP-970): Updated 2.2 Tableau connectivity.

- source/connect/mysql.txt
- source/reference/auth-plugin-c.txt
- source/tutorial/install-auth-plugin-c.txt
@jeff-allen-mongo : Added information on Windows 32-bit support for BI Connector and a few Windows examples.
> (DOCS-10897, DOCSP-1091, -1281): Added Windows examples, 32-bit compatibility. SSL Compatibility.

- source/supported-operations.txt
@jeff-allen-mongo : Quick change for you. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-1287/supported-operations.html#comparison-functions-and-operators).
> (DOCSP-1287,-88): Added INTERVAL, MICROSECOND to supported SQL operations

- source/includes/options-mongosqld.yaml
Added `USING` to supported options and fixed error with `mongosqld`.
> (DOCSP-1051): Added USING to supported operations.

- source/reference/mongosqld.txt
- source/schema-configuration.txt
@steveren : Could you give this a quick look? It adds permissions explanations for [Cached Sampling](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-1364/schema-configuration.html#user-permissions) and [Persistent Schema](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-1364/schema-configuration.html#id1).
> (DOCSP-1364): Add permissions for Schema gen.

- source/installation.txt
- source/launch.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/126)
> DOCSP-2217 - No longer supporting SUSE11 and Debian 7.1

- source/includes/options-mongosqld.yaml
- source/reference/mongosqld.txt
@rychipman : I have provided all of the options. I still have a question posted to you in JIRA for DOCSP-2437 about where in the conf file these values would go. Please have a look. 
- [Kerberos Options](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-2437/reference/mongosqld.html#kerberos-options)
- [Kerberos in Security Options for Conf file](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-2437/reference/mongosqld.html#security-options)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/140)
> (DOCSP-2437): Added Kerberos options.

- source/index.txt
- source/reference.txt
- source/supported-operations.txt
Staged: [GROUP BY (Aggregate) Functions](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/steverenaker/DOCSP-3526/supported-operations.html#group-by-aggregate-functions)
> DOCSP-3526: [BIC] Support GROUP_CONCAT aggregate function

- source/launch.txt
@nlarew : This adds `sudo` to the Debian and RHEL tabs of the [Install mongosqld as a System Service](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-12418/launch.html#install-mongosqld-as-a-system-service) section.
> (DOCS-12418): Add sudo to system service commands.

- conf.py
- source/tutorial/kerberos.txt
Added notes to Windows setup for Linux clients. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-4787/tutorial/kerberos.html)
> (DOCSP-4787): Added Kerberos for Linux caveats.

- source/includes/fact-sampleRefresh.rst
- source/includes/fact-samplemode-write-permission.rst
- source/includes/options-mongosqld.yaml
- source/includes/sampleSource-example.rst
- source/includes/schemaSource-example.rst
- source/reference/mongosqld.txt
- source/reference/user-authorization.txt
- source/schema-configuration.txt
- source/schema/cached-sampling.txt
- source/schema/persist-schema.txt
- source/schema/resample-schema.txt
- source/schema/type-conflicts.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-5779
**Staging**
- `--schemaMode` : https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-5779/reference/mongosqld.html#cmdoption-mongosqld-schemamode
- `--schemaSource` : https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-5779/reference/mongosqld.html#cmdoption-mongosqld-schemasource
- `--schemaName` : https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-5779/reference/mongosqld.html#cmdoption-mongosqld-schemaname
- Config file settings: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-5779/reference/mongosqld.html#data-sampling-options
- Schema Sampling Reference Chart: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdeste …
> DOCSP-5779 - Update mongosqld command line options and config file settings.

- snooty.toml
Most repos I've seen don't include `docs-` in the slug defined in their snooty.toml. If this change wouldn't break anything, I propose standardizing our naming scheme.
> Modify snooty.toml slug

- source/includes/options-mongosqld.yaml
- source/reference/mongosqld.txt
- source/tutorial/kerberos.txt
Staged: [mongosqld](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-5844/reference/mongosqld.html#cmdoption-mongosqld-gssapiconstraineddelegation)
> [BIC] Only use GSSAPI proxy creds for constrained delegation

- source/includes/steps-create-system-dsn-macos.yaml
- source/includes/temp-warn-odbc-catalina.txt
- source/reference/odbc-driver.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-7244)
Added warning file 'temp-warn-odbc-catalina'
Warning file included on:
- Components/[MongoDB ODBC Driver page](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/zach.carr/DOCSP-7244/reference/odbc-driver.html)
- [Create a System DSN](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/zach.carr/DOCSP-7244/tutorial/create-system-dsn.html), under macOS tab
> (DOCSP-7244) Add incompatibility warning for ODBC Manager with macOS Catalina

- source/includes/steps-create-system-dsn-macos.yaml
- source/includes/temp-warn-odbc-catalina.txt
- source/reference/odbc-driver.txt
These changes have already been internally reviewed [here](https://github.com/mongodb/docs-bi-connector/pull/239). I merged that PR before external review by mistake, reverted, and opened this PR for external review.
[Ticket](https://jira.mongodb.org/browse/DOCSP-7244)
Added file 'temp-warn-odbc-catalina' that creates an admonition
Admonition on:
- Components/[MongoDB ODBC Driver page](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/zach.carr/DOCSP-7244/reference/odbc-driver.html)
- [Create a System DSN](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/zach.carr/DOCSP-7244/tutorial/create-system-dsn.html), under macOS tab
> (DOCSP-7244) Add incompatibility warning for ODBC Manager with macOS Catalina (after revert)

- config/build_conf.yaml
- config/redirects
- source/includes/fact-system-vars.rst
- source/release-notes.txt
I've omitted items which refer to concepts which don't exist in the docs.
Staged: [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-7669/release-notes.html)
> DOCSP-7669: BI Connector v2.13 release notes

- source/reference/auth-plugin-c.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-12075)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-12075/reference/auth-plugin-c.html)
> DOCSP-12075: [BI Connector] Mongosql-auth-c in MacOS Catalina requires OpenSSL v1.0

- snooty.toml
- source/atlas-bi-connector.txt
- source/authentication.txt
- source/client-applications.txt
- source/components.txt
- source/connect/tableau-no-auth.txt
- source/connect/tableau.txt
- source/includes/c-auth-supported-platforms.rst
- source/includes/fact-mongodrdl-example.rst
- source/includes/fact-v210-schema-options.rst
- source/includes/steps-local-quickstart.yaml
- source/index.txt
- source/installation.txt
- source/launch.txt
- source/reference.txt
- source/reference/auth-plugin-jdbc.txt
- source/reference/mongodrdl.txt
- source/reference/mongosqld.txt
- source/reference/mongotranslate.txt
- source/release-notes.txt
- source/schema-configuration.txt
- source/tutorial/create-system-dsn.txt
- source/tutorial/kerberos.txt
- worker.sh
Workerpool log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f4fe51a0636c3a9b68f2e06
Staging: https://docs-mongodborg-staging.corp.mongodb.com/3498fd9/bi-connector/docsworker-xlarge/snooty/
- the `container` directive is deprecated -- y'all are using the container directive to indent nested steps, I've filed [DOP-1449](https://jira.mongodb.org/browse/DOP-1449) to look at whether there's a better way for us to do this. All the same, the content is rendering like it did in oldgen, so nothing really to worry about.
- [DOCSP-12086](https://jira.mongodb.org/browse/DOCSP-12086)Broken links - there are a bunch of ambiguous/broken links to settings, options, etc. some of them (e.g. the urioption ones) are broken on the live site as well, so I suspect this is a case of Snooty …
> DOP-1345: build BI Connector on snooty

- source/launch.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-13490)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/26ce7af/bi-connector/docsworker-xlarge/DOCSP-13490/launch#launching-mongosqld)
> DOCSP-13490: [BIC] Missing instruction for installing biconnector as service on RHEL

- source/release-notes.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-15265)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/d3ee190/bi-connector/docsworker-xlarge/DOCSP-15265/release-notes/)
Hi @rychipman, would you please review these release notes whenever you get a moment? 
I left out the following because they don't seem to need release notes, please let me know if any should be included:
- [BI-2335] - IN clause casting mismatch (closed as Won't Fix)
- [BI-2624] - Platforms missing on downloads site
- [BI-2476] - Use macos 10.14 instead of 10.12 for evergreen testing
- [BI-2616] - Stop using mongodbtoolchain
- [BI-2619] - Rely on mongo-tools instead of mongo-tools-common
> (DOCSP-15265) 2.14.3 release notes

- source/includes/geospatial-data.rst
[JIRA](https://jira.mongodb.org/browse/DOCSP-17899)
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-17889/schema/geospatial-data/)
tested new command:
```
MongoDB Enterprise atlas-wd1p6t-shard-0:PRIMARY>    db.points.insertOne({
...        pos : { type: "Point", coordinates: [ -73.97, 40.77 ] },
...        name: "Central Park",
...        category : "Parks"
...    })
{
"acknowledged" : true,
"insertedId" : ObjectId("6112936aa6b0bba12a00cb0c")
}
```
> (DOCSP-17899): remove deprecated crud commands from bi connector docs

- source/atlas-bi-connector.txt
- source/includes/atlas-bi-connector.rst
- source/what-is-the-bi-connector.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-18336)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-18336/what-is-the-bi-connector/)
Note for copy review: this is mostly moving things around. The small amount of new copy is in the BI configuration descriptions, everything else is just switching the order or removing things.
- Moved the configuration types under an umbrella header and added a ToC to the page to better group and distinguish them from the rest of the page.
- Changed mentions of ODBC/ creating a DSN for ODBC to more general statements about connecting with ODBC or JDBC.
- Reorganized the Components section. Screenshot now appears under the components, component order changed to match.
- In order to reduce note clutter, I …
> (DOCSP-18336) Clarify and generalize BIC configurations

- source/includes/steps-install-bi-connector-macos.yaml
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6356aca37f102f5cea12b05a)
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-23677)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-23677/tutorial/install-bi-connector-macos/#install-the-bi-short)
I tested this code myself and confirmed that it works on my Mac.
> (DOCSP-23677) Updates Mac install instructions to use zip archive

- source/release-notes.txt
@JuliaMongo, I added a release note item for the removed support for RHEL6/7 on S390x.
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-26278/release-notes/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-26278)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=636c02707f102f5ceaf82173)
> (DOCSP-26278): Added release note item for removed support.

- source/includes/steps-mac-ssl-config.yaml
- source/includes/steps-windows-ssl-config.yaml
[Fix June batch of 404s](https://jira.mongodb.org/browse/DOCSP-30712)
I updated the links to the intended destinations. Example: 
Old https://www.mongodb.com/docs/manual/reference/program/mongod/index.html#cmdoption-mongod-tlsmode
New https://www.mongodb.com/docs/manual/reference/program/mongod/#std-option-mongod.--tlsMode
> (DOCSP-30712) Fix BIC 404s

- source/includes/options/option-mongosqld-filePermissions.rst
Update default file permission from 448 to 0700.
Slack thread for reference: https://mongodb.enterprise.slack.com/archives/C0V5DQ8KD/p1702938349479769
[JIRA](https://jira.mongodb.org/browse/DOCS-12116)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6580cbdc7a5cb5fef56b5105)
[STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/bi-connector/DOCS-12116/reference/mongosqld/#socket-options)
> (DOCS-12116) update default file permission from 448 to 0700

- source/reference/jdbc-driver.txt
Updated both links on the JDBC page. 
And from [this BI ticket](https://jira.mongodb.org/browse/BI-2838), I also updated the minimum version to 5.1.44
[JIRA](https://jira.mongodb.org/browse/DOCSP-35199)
[Staging](https://preview-mongodbkyuanmongodb.gatsbyjs.io/bi-connector/DOCSP-35199/reference/jdbc-driver/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a7f535dcc0144a5153265e)
> DOCSP-35199 jdbc link fixes

- source/reference/mongodrdl.txt
- source/reference/mongosqld.txt
- source/reference/mongotranslate.txt
https://jira.mongodb.org/browse/DOCSP-36779
The Smartling translation software is reading page metadata, and these metadata tags are causing problems.
`man page`
> Docsp 36779

- .vscode/settings.json
- source/reference.txt
- source/reference/known-issues.txt
Add workaround for 'Mapping Potentially Null Values at Different Object Depths' to Known Issues.
[JIRA](https://jira.mongodb.org/browse/DOCSP-35411)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65de1f3e7111165982c96410)
[STAGING](https://preview-mongodbjvincentmongodb.gatsbyjs.io/bi-connector/DOCSP-35411/reference/known-issues/#mapping-potentially-null-values-at-different-object-depths)
> DOCSP-35411 -- Add workaround for 'Mapping Potentially Null Values at Different Object Depths' to Known Issues.

- source/includes/temp-warn-odbc-catalina.rst
Updated the macOS catalina warning to also mention it won't work for future macOS versions.
[JIRA](https://jira.mongodb.org/browse/DOCS-15921)
[Staging](https://preview-mongodbkyuanmongodb.gatsbyjs.io/bi-connector/DOCS-15921/reference/odbc-driver/#supported-platforms)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ea3ed66fc5f048506b85be)
> DOCS-15921 macOS catalina warning update

- source/reference/mongodrdl.txt
This PR adds a note that .drdl file can't be used in Atlas BI Connector. 
It is similar to an Atlas-side PR on the same.
[DOCSP-40367](https://jira.mongodb.org/browse/DOCSP-40367)
[Staging](https://preview-mongodbjuliamongo.gatsbyjs.io/bi-connector/DOCSP-40367/reference/mongodrdl/#mongodb-atlas-example:~:text=MongoDB%20Atlas%20offers%20a%20hosted%20BI%20Connector.%20You%20can%27t%20use%20the%20.drdl%20file%20output%20of%20the%20mongodrdl%20command%20in%20the%20Atlas%2Dhosted%20BI%20Connector.%20Atlas%20BI%20Connector%20requires%20sampling%20that%20has%20an%20adjustable%20sample%20refresh%20interval%20and%20sample%20size.)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=666bbc79ebce19f314bff41f)
> (DOCSP-40367) cannot use drdl file in Atlas BIC

- source/release-notes.txt
Added the v2.14.13 release notes.
[JIRA](https://jira.mongodb.org/browse/DOCSP-43801)
[Staging](https://deploy-preview-444--mongodb-docs-bi-connector.netlify.app/release-notes/#bi-2.14.13)
> DOCSP-43801 added bic v2.14.13 rn

- source/includes/steps-create-system-dsn-auth-macos.rst
- source/includes/steps-create-system-dsn-auth-ssl-macos.rst
- source/includes/steps-create-system-dsn-macos.rst
- source/includes/steps-create-system-dsn-no-auth-macos.rst
- source/includes/steps-install-bi-connector-debian.yaml
- source/includes/steps-install-bi-connector-macos.yaml
- source/includes/steps-install-bi-connector-rhel.yaml
- source/schema/cached-sampling.txt
Also fixes some preexisting build errors due to monospace backticks missing and an ambiguous reference. Remaining 2 preexisting errors need investigation and are outside the scope of this ticket.
[DOCSP](https://jira.mongodb.org/browse/DOCSP-44175)
Staging Links:
https://deploy-preview-447--mongodb-docs-bi-connector.netlify.app/connect/tableau-auth
https://deploy-preview-447--mongodb-docs-bi-connector.netlify.app/connect/tableau-auth-ssl
https://deploy-preview-447--mongodb-docs-bi-connector.netlify.app/connect/tableau-no-auth
https://deploy-preview-447--mongodb-docs-bi-connector.netlify.app/tutorial/create-system-dsn
> (DOCSP-44175) Fixes final important nested components for BIC

- source/connect/mysql.txt
MySQL updated its documentation and moved a couple of pages.
Update the link behind "MySQL documentation" from "https://dev.mysql.com/doc/refman/5.7/en/cleartext-authentication-plugin.html" to "https://dev.mysql.com/doc/mysql-security-excerpt/en/cleartext-pluggable-authentication.html"
The section is at the bottom of the page.
> See the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/cleartext-authentication-plugin.html) for additional details on enabling the MySQL cleartext plugin.
- [DOCSP-47223](https://jira.mongodb.org/browse/DOCSP-47223)
- [STAGING](https://deploy-preview-454--docs-bi-connector.netlify.app/connect/mysql/)
> (DOCSP-47223) [BIC] Update outdated link on BI Connector documentation

- source/reference/known-issues.txt
... to avoid incomplete number of documents in view with null values.
[DOCSP-48691](https://jira.mongodb.org/browse/DOCSP-48691)
[STAGING](https://deploy-preview-457--docs-bi-connector.netlify.app/reference/known-issues/#bi-connector-returns-null-values-due-to-mapping-error)
> DOCSP-48691 -- Changed code example... 
