- source/faq.txt
- source/reference/mongosqld.txt
@i80and : Can you review this? [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-9253/reference/mongosqld.html)
> (DOCS-9253): Added allowDiskUse to mongosqld page.

- source/includes/steps-install-bi-connector.yaml
@i80and : Can you see if this looks correct? I did base it on my work with Ops Manager installs.
> (DOCSP-335): Update with Windows install.

- source/tutorial/connecting-to-atlas.txt
@i80and : Please review at your convenience. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-9929/tutorial/connecting-to-atlas.html). This staging is goofed up because the `make html` command generated [this error](https://gist.github.com/atsansone/150c87a0daab7e5a1ab805c78f244fb2).
> (DOCS-9929): Added note about Atlas free tier.

- source/includes/options-mongosqld.yaml
- source/reference/mongosqld.txt
- source/tutorial/connecting.txt
@i80and : My reading of the ticket puts this as a reference change. Please have a look.
> (DOCSP-754): Added default settings.

- source/includes/steps-install-bi-connector.yaml
- source/installation.txt
@craiggwilson : I am going to tech review first because we have been actively discussing this today. The changes are [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-753/installation.html).
> (DOCSP-753): Added Windows service install.

- source/release-notes.txt
@breinero : Please review. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-1111/release-notes.html).
> (DOCSP-1111): Release Notes for 2.2.1

- source/reference/mongodrdl.txt
> DOCSP-1168: error fixes for custom filter example

- source/release-notes.txt
@craiggwilson : These are the release notes for 2.3 and 2.3.1. [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-11009/release-notes.html).
> (DOCS-11009): Release Notes for 2.3 and 2.3.1

- Makefile
- config/redirects
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/87)
> DOCSP-1603 - Added redirects for content reorg.

- source/includes/steps-install-bi-connector-debian.yaml
- source/includes/steps-install-bi-connector-macos.yaml
- source/includes/steps-install-bi-connector-rhel.yaml
- source/includes/steps-install-bi-connector-windows.yaml
- source/includes/steps-install-bi-connector.yaml
- source/tutorial/install-bi-connector-debian.txt
- source/tutorial/install-bi-connector-macos.txt
- source/tutorial/install-bi-connector-rhel.txt
- source/tutorial/install-bi-connector-windows.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/88)
> Docsp 1641

- source/includes/steps-connect-tableau-mongosql-plugin.yaml
@nlarew : Should be straightforward. [Staged.](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCS-11125/connect/tableau.html#create-a-tableau-datasource-connection-file)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/80)
> (DOCS-11125): Add note about Tableau repository.

- source/client-applications.txt
- source/client-dependencies.txt
- source/components.txt
- source/connect/mysql.txt
- source/includes/auth-info.rst
- source/includes/auth-intro-c.rst
- source/includes/auth-intro-jdbc.rst
- source/includes/fact-auth-mechanisms.rst
- source/includes/steps-install-bi-connector-debian.yaml
- source/includes/toc-client-applications.yaml
- source/includes/toc-client-dependencies.yaml
- source/index.txt
- source/reference/auth-plugin-c-mysql-options.txt
- source/reference/auth-plugin-c.txt
- source/reference/auth-plugin-jdbc.txt
- source/tutorial/install-auth-plugin-c.txt
- source/tutorial/install-auth-plugin-jdbc.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/105)
> DOCSP-1685 - Renamed nav items. Deduped C Auth Plugin page.

- source/schema-configuration.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/101)
> DOCSP-1243: BI Connector: using views instead of .drdl files

- source/reference/mongosqld.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/108)
> DOCSP-1897: fix verbosity line in example configuration file

- source/atlas-bi-connector.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/109)
> Fix broken link to installation guides on Atlas page.

- source/connect/mysql.txt
- source/faq.txt
- source/includes/fact-geospatial-views.rst
- source/includes/geospatial-data.rst
- source/includes/steps-install-bi-connector-debian.yaml
- source/includes/steps-install-bi-connector-macos.yaml
- source/includes/steps-install-bi-connector-rhel.yaml
- source/includes/steps-install-bi-connector-windows.yaml
- source/includes/steps-local-quickstart.yaml
- source/reference/drdl.txt
- source/reference/log-messages.txt
- source/schema-configuration.txt
- source/tutorial/install-auth-plugin-jdbc.txt
- source/tutorial/install-bi-connector-debian.txt
- source/tutorial/install-bi-connector-macos.txt
- source/tutorial/install-bi-connector-rhel.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/110)
> DOCSP-1971: 2d/2dsphere index behavior

- source/release-notes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/111)
> DOCSP-2045 - Release notes for version 2.4.1

- source/includes/options-mongosqld.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/112)
> DOCSP-1988: BIC connect=direct URI option

- source/launch.txt
- source/tutorial/install-bi-connector-macos.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/114)
> DOCSP-2081: Launch BIC: miscellaneous improvements

- source/components.txt
- source/includes/fact-samplemode-write-permission.rst
- source/includes/options-mongosqld.yaml
- source/includes/sampleSource-example.rst
- source/includes/sampling-ref-chart-link.rst
- source/includes/user-permissions.rst
- source/reference/mongosqld.txt
- source/schema-configuration.txt
- source/tutorial/install-bi-connector-debian.txt
- source/tutorial/install-bi-connector-macos.txt
- source/tutorial/install-bi-connector-rhel.txt
- source/tutorial/install-bi-connector-windows.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/115)
> Docsp 1585

- source/connect/tableau.txt
- source/includes/client-prereqs.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/116)
> DOCS-11258: add mysql driver prereq to Tableau instructions

- source/client-dependencies.txt
- source/connect/excel.txt
- source/connect/microstrategy.txt
- source/connect/mysql.txt
- source/connect/powerbi.txt
- source/connect/qlik.txt
- source/connect/spotfire-cloud.txt
- source/connect/tableau.txt
- source/includes/auth-intro-c.rst
- source/includes/auth-intro-jdbc.rst
- source/includes/auth-options.rst
- source/includes/client-connect-prereqs.rst
- source/includes/client-connection-prereqs.rst
- source/includes/fact-mysql-config-mac-linux-only.rst
- source/includes/fact-plugin-directory-windows.rst
- source/includes/steps-connect-qlik-plugin.yaml
- source/includes/steps-connect-tableau-102-authentication-tdc.yaml
- source/includes/steps-connect-tableau-103-authentication-tdc.yaml
- source/includes/steps-connect-tableau-authentication-envvar.yaml
- source/includes/steps-connect-tableau-mongosql-plugin.yaml
- source/includes/steps-connect-tableau-without-auth.yaml
- source/includes/steps-create-system-dsn-auth.yaml
- source/includes/tableau-default-tdc-locations.rst
- source/includes/toc-reference-landing.yaml
- source/index.txt
- source/launch.txt
- source/reference.txt
- source/reference/auth-plugin-c-mysql-options.txt
- source/reference/authentication.txt
- source/tutorial/install-auth-plugin-c.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/117)
> DOCSP-1558 - Cleaned up BI tool connect tutorials and auth plugin page.

- source/includes/options-shared.yaml
- source/launch.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/122)
> DOCS-11553: BI Connector docs inconsistencies

- source/connect/tableau.txt
- source/includes/steps-connect-tableau-mongosql-plugin.yaml
Code review: https://mongodbcr.appspot.com/196750001/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jeffreyallen/DOCS-11305/connect/tableau.html#connect-from-tableau-with-the-c-authentication-plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/123)
> DOCS-11305 - Adding step to change file permissions for mysql config file

- source/connect/mysql.txt
- source/includes/c-auth-supported-platforms.rst
- source/includes/client-prereqs.rst
- source/includes/fact-c-auth-compatibility.rst
- source/includes/fact-mysql-odbc-version-reqs.rst
- source/reference/auth-plugin-c.txt
- source/tutorial/create-system-dsn.txt
- source/tutorial/install-auth-plugin-c.txt
Code review: https://mongodbcr.appspot.com/200400001/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jeffreyallen/DOCS-11638/tutorial/create-system-dsn.html
https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jeffreyallen/DOCS-11638/connect/tableau.html
https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jeffreyallen/DOCS-11638/connect/mysql.html#connect-from-mysql-with-authentication
https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jeffreyallen/DOCS-11638/tutorial/install-auth-plugin-c.html
https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jeffreyallen/DOCS-11638/reference/auth-plugin-c.html#supported-platforms
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> DOCS-11638 - Updating links to odbc ver 5.3.10 and updating notes regarding compatibility

- source/includes/options-mongosqld.yaml
- source/reference/mongosqld.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/130)
> DOCSP-2192: extend --sampleNamespaces to support exclusion

- source/reference/log-messages.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/131)
> DOCSP-2141: BI Connector: change to logfile name format

- source/launch.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/134)
> DOCS-11546: BI Connector - Launch Page Improvements

- config/build_conf.yaml
- config/redirects
- source/includes/options-mongosqld.yaml
- source/installation.txt
- source/launch.txt
- source/reference/log-messages.txt
- source/reference/mongosqld.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/135)
> 2.5 upcoming tickets

- source/reference/mongosqld.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/142)
> DOCSP-2498: Incorrect flag option types

- source/reference/mongosqld.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/143)
> DOCSP-2498-v2.4: Incorrect flag option types

- config/integration.yaml
- source/reference/mongosqld.txt
- source/release-notes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/144)
> DOCS-11684 - Release notes for v2.5

- source/includes/steps-connect-tableau-mongosql-plugin-macos.yaml
- source/includes/steps-connect-tableau-mongosql-plugin-windows.yaml
- source/includes/steps-connect-tableau-mongosql-ssl-macos.yaml
- source/includes/steps-connect-tableau-mongosql-ssl-windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/147)
> Fix styling for nested steps

- source/installation.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jeffreyallen/DOCSP-2438/installation.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/141)
> DOCSP-2438 - Updates to supported platforms matrix

- config/build_conf.yaml
- config/integration.yaml
- config/redirects
- source/components.txt
- source/faq.txt
- source/includes/client-prereqs.rst
- source/includes/steps-connect-tableau-mongosql-plugin.yaml
- source/launch.txt
- source/reference/mongosqld.txt
- source/reference/odbc-driver.txt
- source/release-notes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/152)
> Docsp 2485

- config/redirects
- source/includes/fact-ansi-unicode-driver.rst
- source/includes/steps-create-system-dsn-macos.yaml
- source/includes/steps-create-system-dsn.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongodb/docs-bi-connector/155)
> DOCS-11756 - ANSI vs. Unicode clarifications.

- source/connect/excel.txt
CR: https://mongodbcr.appspot.com/211430001/
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jeffreyallen/DOCS-11775/connect/excel.html
> DOCS-11775 - Adding output table for Excel version command

- source/index.txt
Hey @jdestefano-mongo the Atlas SWAT team wants to place some calls to actions (CTAs) in some highly trafficked / Atlas relevant sections of the Docs. The homepage of the BI Connector Docs is one of those pages. Over the next few weeks we'll see how this CTA performs and will experiment with variants accordingly.
Can you review these changes?
Changes staged at the following page:
https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/kirby/kk-20-docs-in-20-days-phase-1/index.html
> Add note for phase 1 of 20 docs in 20 days

- conf.py
- source/includes/atlas-bi-connector.rst
- source/includes/steps-create-system-dsn.yaml
- source/includes/steps-mac-ssl-config.yaml
- source/includes/steps-windows-ssl-config.yaml
- source/includes/toc-client-applications.yaml
- source/includes/toc-install.yaml
- source/installation.txt
- source/launch.txt
- source/reference/odbc-driver.txt
- source/release-notes.txt
- source/schema/persist-schema.txt
- source/tutorial/install-bi-connector-debian.txt
- source/tutorial/install-bi-connector-macos.txt
- source/tutorial/install-bi-connector-rhel.txt
- source/tutorial/install-bi-connector-windows.txt
- source/tutorial/ssl-setup.txt
This is an old ticket that was done but never merged. I put the old changes into a new branch rather than try to bring the old branch up to date.
> DOCSP-1881: consistent abbreviations

- source/release-notes.txt
https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-3409/release-notes.html#bi-2-7-0
> DOCSP-3409 - BIC 2.7.0 Release Notes

- source/includes/steps-create-system-dsn-linux.yaml
- source/tutorial/create-system-dsn.txt
Staged: [Create a System DSN](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/steverenaker/DOCS-12037/tutorial/create-system-dsn.html)
> DOCS-12037: [BIC] Create a DSN Procedure for Linux

- source/client-applications.txt
Staged at https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/robertjustice/DOCSP-3556/client-applications.html#certified-partner-tools.
> (DOCSP-3556) Added Qlik Sense to list of certified parter tools.

- source/supported-operations.txt
Staged: [Supported SQL Functions and Operators](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/steverenaker/DOCSP-3499/supported-operations.html#database-administration-statements)
> DOCSP-3499: [BIC] Support altering type for a given column

- source/reference/user-authorization.txt
- source/release-notes.txt
- source/supported-operations.txt
Staged:
[Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/steverenaker/DOCSP-3657/release-notes.html)
[User Authorization Model](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/steverenaker/DOCSP-3657/reference/user-authorization.html)
> DOCSP-3657: [BIC] v2.8 release notes and a correction

- source/release-notes.txt
Staged: [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/steverenaker/DOCSP-3657/release-notes.html)
> DOCSP-3669: [BIC] Update to BIC Release Notes

- source/includes/steps-create-system-dsn-linux.yaml
isql had issues connecting to remote servers.
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-3850/tutorial/create-system-dsn.html
> DOCSP-3850 - Update Linux DSN to test with iusql.

- source/includes/steps-create-system-dsn-linux.yaml
Staged: [Create a System DSN](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/steverenaker/DOCSP-3708/tutorial/create-system-dsn.html)
> DOCSP-3708: [BIC] Document SSL related DSN configuration options for ODBC driver

- source/includes/fact-ansi-unicode-driver.rst
- source/includes/steps-create-system-dsn-linux.yaml
Staged: [Create a System DSN](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/steverenaker/DOCSP-3977/tutorial/create-system-dsn.html)
> DOCSP-3977: [BIC] Update Linux DSN tutorial based on S&T feedback

- source/release-notes.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-3983/release-notes.html
> DOCSP-3983 - BIC 2.9.0 Release Notes

- source/includes/sample-config.rst
- source/tutorial/install-bi-connector-debian.txt
- source/tutorial/install-bi-connector-macos.txt
- source/tutorial/install-bi-connector-rhel.txt
- source/tutorial/install-bi-connector-windows.txt
Staged: [Install BI Connector On Premises](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/steverenaker/DOCSP-3833/tutorial/install-bi-connector-windows.html)
> DOCSP-3833: [BIC] Package example mongosqld.conf with download bundle

- source/reference/known-issues.txt
- source/release-notes.txt
@rychipman : This has been outstanding a while and I know that it has no resolution yet (BI-484), but could you take a look at this [added known issues page](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-1089/reference/known-issues.html) and the first known issue listed to see if I have this correct?
> (DOCSP-1089): Added known issue on GROUP BY.

- source/installation.txt
@nlarew : [This](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-4251/installation.html#supported-platforms) updates the supported platforms to make clear which versions we support.
> (DOCSP-4251): Fixed Supported Platforms.

- source/includes/options-mongosqld.yaml
Staged: [mongosqld](https://docs-mongodborg-staging.corp.mongodb.com/bi-connector/steverenaker/DOCSP-4549/index.html)
> DOCSP-4549: [BIC] SSL description references MySQL Server

- config/build_conf.yaml
- config/integration.yaml
- config/redirects
- source/release-notes.txt
JIRA: 
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-4898/release-notes.html#bi-2-10-0
Related docs-tools PR: https://github.com/mongodb/docs-tools/pull/271
> DOCSP-4898 - v2.10.0 release notes.

- snooty.toml
- source/release-notes.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-5587
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-5587/release-notes.html#bi-2-11-0
**Note to Docs:** THIS MUST BE MERGED WITH https://github.com/mongodb/docs-tools/pull/292
> DOCSP-5587 - 2.11 release notes.

- source/release-notes.txt
Staged: [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-6073/release-notes.html)
> DOCSP-6073: BI Connector v2.11.1 Release Notes

- conf.py
- source/tutorial/kerberos.txt
@beergeek : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/anthonysansone/DOCSP-6183/tutorial/kerberos.html) your requested changes.
> (DOCSP-6183): Added Kerberos ADC constraints.

- source/includes/fact-polymorphic-type-conversion-mode.rst
- source/includes/fact-type-conversion-mode.rst
- source/includes/options-mongosqld.yaml
- source/reference/mongosqld.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-3832
Staged:
- Configuration file setting: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-3828/reference/mongosqld.html#set-parameter-options
- Command-line option: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-3828/reference/mongosqld.html#set-parameter-option
> DOCSP-3828 - Add Set Parameter configuration file options.

- snooty.toml
Add source constants as defined in [conf.py](https://github.com/mongodb/docs-bi-connector/blob/master/conf.py#L96-L104).
> Add source constants to snooty.toml

- source/includes/fact-system-vars.rst
Staged: [System Variables](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-4340/reference/system-variables.html)
> DOCSP-4340: [BIC] List supported MySQL global variables

- source/includes/fact-system-vars.rst
Staged: [System Variables](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-3718/reference/system-variables.html)
> DOCSP-3718: [BIC] max_execution_time system variable

- config/build_conf.yaml
- config/integration.yaml
- config/redirects
- source/release-notes.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-6928
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker/DOCSP-6928/release-notes.html#bi-2-12
> DOCSP-6928 - 2.12 release notes

- source/includes/fact-mongodrdl-schema-name.rst
- source/includes/options-mongodrdl-commands.yaml
- source/includes/options-mongodrdl.yaml
- source/includes/options-mongosqld.yaml
- source/includes/options-shared.yaml
- source/reference/mongodrdl.txt
- source/schema/load-schema-from-drdl.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-5781
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/jdestefano/DOCSP-5781/reference/mongodrdl.html
> DOCSP-5781 - mongodrdl schema management changes.

- source/includes/steps-create-system-dsn-macos.yaml
- source/includes/temp-warn-odbc-catalina.txt
- source/reference/odbc-driver.txt
Reverts mongodb/docs-bi-connector#239
Needs external review
> Revert "(DOCSP-7244) Add incompatibility warning for ODBC Manager with macOS Catalina"

- source/includes/options-mongodrdl.yaml
- source/reference/mongodrdl.txt
Staged: [mongosqld](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-6931/reference/mongodrdl.html#command-line-options)
> DOCSP-6931: [BI Connector] new mongodrdl options

- source/includes/fact-system-vars.rst
- source/release-notes.txt
Staged: 
https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-7903/release-notes.html
https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-7903/reference/system-variables.html
> [BIC] v2.13.1 Release Notes

- source/release-notes.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-8953/release-notes.html
> DOCSP-8953: [BIC] Release notes for v2.13.4

- source/release-notes.txt
- source/schema-configuration.txt
Staged: [Release Notes](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-11186/release-notes.html)
> DOCSP-11186: [BI Connector] release notes for 2.14

- source/includes/options/option-mongosqld-usageLogInterval.rst
- source/reference/mongosqld.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-9094)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-9094/reference/mongosqld.html#cmdoption-mongosqld-usageloginterval)
> DOCSP-9094: [BI Connector] Periodically print out usage stats

- source/index.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-6685)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/stevenrenaker/DOCSP-6685/index.html)
> DOCSP-6685: [BIC] Mention Charts on BI Connector main page

- conf.py
- source/reference/auth-plugin-jdbc.txt
@steveren : Added this to the [Prerequisites](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-4788/reference/auth-plugin-jdbc.html#prerequisites).
---
[Builds without errors on `master`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f4fef640636c3a9b690cacb)
> (DOCSP-4788) Add Connector/J 5.1.39 req

- conf.py
- source/atlas-bi-connector.txt
- source/includes/atlas-bi-connector.rst
@steveren : I'm going with a [minor change](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-5797/atlas-bi-connector.html) because of the future of this product. I think this meets the need without needing a refactor to highlight the issue further. 
---
[Builds without errors on `master`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f59010072272277501d4b5f)
> (DOCSP-5797) Add CM/OM items

- conf.py
- source/includes/steps-mac-ssl-config.yaml
- source/includes/steps-windows-ssl-config.yaml
- source/includes/styles/corrections.rst
- source/index.txt
- source/tutorial/ssl-setup.txt
@steveren : Updated the [TLS config page](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-8993/tutorial/ssl-setup.html#start-mongosqld).
---
[Builds without errors on `master`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f6165057851f76f1df22709)
> (DOCSP-8993) Update TLS info

- snooty.toml
- source/authentication.txt
- source/client-applications.txt
- source/components.txt
- source/connect/tableau-no-auth.txt
- source/connect/tableau.txt
- source/includes/c-auth-supported-platforms.rst
- source/includes/fact-mongodrdl-example.rst
- source/includes/steps-local-quickstart.yaml
- source/index.txt
- source/installation.txt
- source/launch.txt
- source/reference.txt
- source/reference/mongodrdl.txt
- source/reference/mongosqld.txt
- source/release-notes.txt
- source/schema-configuration.txt
- source/tutorial/create-system-dsn.txt
- source/tutorial/kerberos.txt
- worker.sh
Staging: https://docs-mongodborg-staging.corp.mongodb.com/78bb951/bi-connector/docsworker-xlarge/snooty-2.10/
Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f58fedb72272277501ce582
> DOP-1345: prep bi-connector current for snooty build

- snooty.toml
- source/connect/tableau-auth-ssl.txt
- source/connect/tableau.txt
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/22c894a/bi-connector/docsworker-xlarge/DOCSP-13111/connect/tableau)
> DOCSP-13111: [BIC] Tableau connection page section headings

- source/reference/mongosqld.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-12957)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/0ee9841/bi-connector/docsworker-xlarge/DOCSP-12957/reference/mongosqld#usage-with-atlas)
> DOCSP-12957: [BIC] update Atlas connection example

- source/release-notes.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-13789)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/429cc39/bi-connector/docsworker-xlarge/DOCSP-13789/release-notes)
> DOCSP-13789: [BI Connector] v2.14.1 release notes

- source/release-notes.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-14159)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/zach.carr/DOCSP-14159/release-notes.html#bi-2-14-2)
Hi @rychipman, would you mind reviewing these 2.14.2 release notes?
I pulled what I thought were the relevant notes from [this Jira page](https://jira.mongodb.org/secure/ReleaseNote.jspa?projectId=13184&version=30354), but I'm not familiar with BI Connector or how the docs are maintained yet (I have a meeting this afternoon to get up to speed). Please let me know if something looks off, thank you!
> (DOCSP-14159) 2.14.2 release notes

- source/installation.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-15030)
[Staged (staged with old tools)](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/zach.carr/DOCSP-15030/installation.html)
> (DOCSP-15030) Remove Supported Platforms section

- source/installation.txt
https://jira.mongodb.org/browse/DOCSP-15069
> (DOCSP-15069) Remove Supported Platforms section (#293)

- source/installation.txt
https://jira.mongodb.org/browse/DOCSP-15070
> (DOCSP-15070) Remove Supported Platforms section (#293)

- source/reference/odbc-driver.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-14150)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/f4214ad/bi-connector/docsworker-xlarge/DOCSP-14150/reference/odbc-driver/)
> (DOCSP-14150) Clarify ODBC driver connection

- source/includes/steps-connect-tableau-mongosql-ssl-macos.yaml
- source/release-notes.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-16223) - requires no doc changes, just updated Release Notes
- [Stage](https://docs-mongodbcom-staging.corp.mongodb.com/42c1da5/bi-connector/docsworker-xlarge/DOCSP-16223/release-notes/#bi-2.14.4)
> DOCSP-16223 Drop support for zSeries platforms

- source/reference/system-variables.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-17384)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-17384/reference/system-variables/#setting-system-variables)
> (DOCSP-17384) Correct role for setting system variable

- source/client-applications.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-17594)
[Stage](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-17594/client-applications/)
> (DOCSP-17594): add note about tools support

- source/release-notes.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-18760)
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-18760/release-notes/#improvements)
> (DOCSP-18760) 2.14.4 release notes

- conf.py
- snooty.toml
- source/release-notes.txt
[Ticket](https://jira.mongodb.org/browse/DOCSP-19430)
[Staging - testable link under prereqs](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-19430/local-quickstart/#prerequisites)
> (DOCSP-19430) Update BIC ODBC driver github repo url

- conf.py
- snooty.toml
- source/release-notes.txt
Subtask: https://jira.mongodb.org/browse/DOCSP-19472
> (DOCSP-9472) Backport BIC ODBC driver github url update to v2.13 

- conf.py
- snooty.toml
- source/release-notes.txt
Subtask: https://jira.mongodb.org/browse/DOCSP-19473
> Backport BIC ODBC driver github url update to v2.12 (#350)

- conf.py
- snooty.toml
- source/release-notes.txt
Subtask: https://jira.mongodb.org/browse/DOCSP-19474
> Backport BIC ODBC driver github url update to v2.11 (#350)

- conf.py
- snooty.toml
- source/release-notes.txt
Subtask: https://jira.mongodb.org/browse/DOCSP-19475
> Backport BIC ODBC driver github url update to v2.10 (#350)

- source/authentication.txt
- source/connect/microstrategy.txt
[Jira ticket](https://jira.mongodb.org/browse/DOCSP-20986)
[Staging link](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-20986/)
> (DOCSP-20986) Fix a rendering issue with ODBC links

- snooty.toml
- source/atlas-bi-connector.txt
- source/authentication.txt
- source/components.txt
- source/connect/microstrategy.txt
- source/includes/atlas-bi-connector.rst
- source/includes/steps-connect-tableau-mongosql-plugin-macos.yaml
- source/includes/steps-connect-tableau-mongosql-plugin-windows.yaml
- source/includes/steps-connect-tableau-mongosql-ssl-macos.yaml
- source/includes/steps-connect-tableau-mongosql-ssl-windows.yaml
- source/includes/steps-connect-tableau-without-auth-macos.yaml
- source/includes/steps-connect-tableau-without-auth-windows.yaml
- source/includes/temp-warn-odbc-catalina.rst
- source/index.txt
- source/installation.txt
- source/reference/jdbc-driver.txt
- source/reference/mongodrdl.txt
- source/reference/odbc-driver.txt
- source/reference/system-variables.txt
- source/release-notes.txt
- source/what-is-the-bi-connector.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/2021-bic-docs-improvements-v2.13/)
> Backport 2021 BIC docs improvements to v2.13

- source/reference/system-variables.txt
- source/what-is-the-bi-connector.txt
> Fix a bad merge during backport

- source/schema/resample-schema.txt
Hi @cbush, I added the required privileges and a link to the following page.
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-22101/schema/resample-schema/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-22101)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6261a9c90fdfea9c37e547b1)
> (DOCSP-22101): Added required privileges and a link.

- source/schema/resample-schema.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=626275260fdfea9c370f3a6c)
> (DOCSP-22180): Backport DOCSP-22101 to v2.13. (#368)

- source/schema/resample-schema.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=626278fe0fdfea9c370ff3e1)
> (DOCSP-221818): Backport DOCSP-22101 to v2.12. (#368)

- source/schema/resample-schema.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62627b910fdfea9c3710741b)
> (DOCSP-22182): Backport DOCSP-22101 to v2.11. (#368)

- source/schema/resample-schema.txt
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62627ddd0fdfea9c3710e851)
> (DOCSP-22183): Backport DOCSP-22101 to v2.10. (#368).

- source/index.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-24965)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63110b4f392ddab27032ce23)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-24965/)
> DOCSP-24965: Fixed landing page button links for BI Connector

- source/index.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-24978)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6312219a392ddab2705d55cc)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-24978/)
> DOCSP-24978: Backport DOCSP-24965 to v2.13

- source/index.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-24979)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63122407392ddab2705ddb42)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-24979/)
> (DOCSP 24979): Backport DOCSP-24965 to v2.12

- source/index.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-24980)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6312264c392ddab2705e6495)
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-24980/)
> (DOCSP-24980): Backport DOCSP-24965 to v2.11

- source/index.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-24981)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63122806392ddab2705f0818)
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-24981/)
> (DOCSP-24981): Backport DOCSP-24975 to v2.10

- source/release-notes.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-24988)
[RN file on the wiki](https://jira.mongodb.org/secure/ReleaseNote.jspa?projectId=13184&version=31662)
R[elease Notes for BI Connector 2.14.5](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-24988/release-notes/#bi-2.14.5)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6321b0829ef0f10115403f6e) is clean.
> (DOCSP-24988) Relnotes for BIC 2.14.5

- source/includes/steps-create-system-dsn.yaml
I removed the specific ODBC versions.
[STAGE](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-27432/tutorial/create-system-dsn/#select-a-from-the-list-of-available-drivers)
[JIRA](https://jira.mongodb.org/browse/DOCSP-27432)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63c8465e0ca3b75c006ab3eb)
> (DOCSP-27432): Removed specific ODBC versions.

- source/includes/steps-create-system-dsn.yaml
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63c852f80ca3b75c006dc079)
> (DOCSP-27473): Backport DOCSP-27432 to v2.13. (#385)

- source/includes/steps-create-system-dsn.yaml
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63c8565d0ca3b75c006e948a)
> (DOCSP-27476): Backport DOCSP-27432 to v2.10. (#385)

- source/includes/steps-create-system-dsn.yaml
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63c855970ca3b75c006e6500)
> (DOCSP-27475): Backport DOCSP-27432 to v2.11. (#385)

- source/release-notes.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-29954)
[Build Log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64792e9e67a273b8163638ca)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-29954/release-notes/)
Unrelated warnings in the build log; no errors.
> (DOCSP-29954) Release note

- source/tutorial/create-system-dsn.txt
[JIRA](https://jira.mongodb.org/browse/DOCS-16014)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ad74b0423952aeb928061d)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-16014/tutorial/create-system-dsn/#prerequisites)
> (DOCSP-16014) clarifies system dsn instructions

- source/release-notes.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-30479)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-16014/release-notes/#bi-2.14.7)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b546208d53f9c4afcfea58)
> (DOCSP-16014) bi connector 2.14.7 RN

- source/release-notes.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-31569)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-31569/release-notes/#bi-2.14.9)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64c1166a87b3b36046278d35)
> (DOCSP-31569) BI connector version 2.14.9 release notes

- snooty.toml
[Jira](https://jira.mongodb.org/browse/DOCSP-30849)
[EOL instructions, step 2](https://wiki.corp.mongodb.com/display/DE/How+To%3A+Sunset+an+EOL+Version+of+Documentation)
Identical PRs for [2.11](https://github.com/mongodb/docs-bi-connector/pull/415/files), [2.12](https://github.com/mongodb/docs-bi-connector/pull/416/files), and [2.13](https://github.com/mongodb/docs-bi-connector/pull/417/files)
> (DOCSP-30849-v2.10) v2.10 EOL

- source/facets.toml
- source/reference/facets.toml
- source/tutorial/facets.toml
Hi @jwilliams-mongo!  This is the *last* set of facet.toml files for the Cloud team.  Please merge if it looks good to you!
Thank you for your help with these!
Sarah
> DOCSP-32482 programmatic tagging script for bi connector repo

- source/release-notes.txt
[Jira](https://jira.mongodb.org/browse/DOCSP-32944)
Is it alright to deviate from the standard of every note being a bullet point? For this case in particular I think a single line with bulleted components makes the most sense.
> (DOCSP-32944) 2.14.11 release notes

- source/includes/steps-create-system-dsn-auth.yaml
- source/includes/steps-create-system-dsn.yaml
[Jira](https://jira.mongodb.org/browse/DOCSP-34616)
[Staging](https://preview-mongodbzachcarr.gatsbyjs.io/bi-connector/DOCSP-34616/connect/tableau-auth/)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655fc07013dc9d16ea86ca20)
> Change misleading title, fix typo

- source/release-notes.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=659daf11dcc0144a519f3291)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/bi-connector/docsworker-xlarge/DOCSP-34941/release-notes/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-34941)
> (DOCSP-34941) RN for BI Connector 2.14.12

- source/includes/options/option-mongosqld-schemaRefreshIntervalSecs.rst
- https://jira.mongodb.org/browse/DOCSP-35264
- [Stage](https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-35264/reference/mongosqld/#std-option-mongosqld.--schemaRefreshIntervalSecs)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667c2a26ebce19f31448aebc) (contains errors and warnings nor introduced by the changes in this PR)
> DOCSP-35264 Clarify the meaning of --schemaRefreshIntervalSecs

- source/includes/steps-install-bi-connector-debian.yaml
- source/includes/steps-install-bi-connector-macos.yaml
- source/includes/steps-install-bi-connector-rhel.yaml
- source/includes/steps-install-bi-connector-windows.yaml
- [JIRA](https://jira.mongodb.org/browse/DOCSP-40387)
- Stage:
- [Windows](https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-40387/tutorial/install-bi-connector-windows/)
- [Mac](https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-40387/tutorial/install-bi-connector-macos/)
- [RHEL](https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-40387/tutorial/install-bi-connector-rhel/)
- [Debian](https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-40387/tutorial/install-bi-connector-debian/)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6675c521ebce19f314edceea)
> DOCSP-40387 Add Verification section to BI Connector installation pages

- source/includes/fact-db-pwd-special-char.rst
- source/includes/steps-create-system-dsn-macos.yaml
- source/includes/steps-create-system-dsn.yaml
- [JIRA](https://jira.mongodb.org/browse/DOCSP-35391)
- [Stage](https://deploy-preview-440--mongodb-docs-bi-connector.netlify.app/tutorial/create-system-dsn/#optional-if-authentication-is-enabled-provide-connection-information,)
- [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66b283fa824f175afd35ce75)
> DOCSP-35391 Mention not to use } char in database password

- source/reference/odbc-driver.txt
- https://jira.mongodb.org/browse/DOCSP-38906
- Stage: https://preview-mongodbkanchanamongodb.gatsbyjs.io/bi-connector/DOCSP-38906/reference/odbc-driver/
- Build Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66d0965bc87522bd3a889524
> DOCSP-38906 Create and Update BIC ODBC Driver workaround

- source/release-notes.txt
[DOCSP 1](https://jira.mongodb.org/browse/DOCSP-43804)
[DOCSP 2](https://jira.mongodb.org/browse/DOCSP-43803)
[DOCSP 3](https://jira.mongodb.org/browse/DOCSP-43802)
[Staging]()
> (DOCSP-43804)(DOCSP-43803)(DOCSP-43802) BI connector release notes for 2.14.14, 2.14.15, and 2.14.16

- source/includes/fact-db-pwd-special-char.rst
[JIRA](https://jira.mongodb.org/browse/DOCSP-42977) 
Staging
- [Connect from Tableau Desktop with Authentication](https://deploy-preview-446--mongodb-docs-bi-connector.netlify.app/connect/tableau-auth/)
- [Connect from Tableau Desktop with Authentication and TLS/SSL](https://deploy-preview-446--mongodb-docs-bi-connector.netlify.app/connect/tableau-auth-ssl/)
- [Create a System DSN](https://deploy-preview-446--mongodb-docs-bi-connector.netlify.app/tutorial/create-system-dsn/)
> DOCSP-42977 removed nested note

- config/redirects
[DOP-5051](https://jira.mongodb.org/browse/DOP-5051)
> Add single-page redirect for v2.1 index to current

- source/includes/auth-intro-jdbc.rst
[JIRA](https://jira.mongodb.org/browse/DOCSP-46225)
[STAGING](https://deploy-preview-452--mongodb-docs-bi-connector.netlify.app/reference/auth-plugin-jdbc/)
> DOCSP-46225 -- fix broken link

- source/connect/powerbi.txt
Notes that [the BI Connector does not work with Direct Query](https://www.mongodb.com/docs/bi-connector/current/connect/powerbi/) in Power BI, and that Atlas SQL supports this feature [now](https://www.mongodb.com/docs/atlas/data-federation/query/sql/powerbi/connect/).
- [DOCSP-41309](https://jira.mongodb.org/browse/DOCSP-41309)
- [STAGING](https://deploy-preview-453--mongodb-docs-bi-connector.netlify.app/connect/powerbi/)
- [LATEST BUILD LOG](https://app.netlify.com/sites/mongodb-docs-bi-connector/deploys/677d4dfbe7d18c00086c34b6)
> (DOCSP-41309) BIC does not work with Direct Query

- source/includes/steps-connect-looker.yaml
[JIRA](https://jira.mongodb.org/browse/DOCSP-38083)
> (DOCSP-38083) Deprecate blacklist and whitelist terminology.

- source/release-notes.txt
- [JIRA](https://jira.mongodb.org/browse/DOCSP-47839)
- [Stage](https://deploy-preview-455--docs-bi-connector.netlify.app/release-notes/)
> DOCSP-47839 BI Connector v2.14.22 RN

- source/reference/mongosqld.txt
[JIRA](https://jira.mongodb.org/browse/DOCS-16975)
[STAGING](https://deploy-preview-458--docs-bi-connector.netlify.app/reference/mongosqld/#mongodb-tls-ssl-options)
> (DOCSP-16975) Adds note about required SSL option.

- snooty.toml
Fixes broken link in[ v2.11 banner](https://www.mongodb.com/docs/bi-connector/v2.11/).
- [DOCSP-48438](https://jira.mongodb.org/browse/DOCSP-48438)
- [STAGING](https://deploy-preview-460--docs-bi-connector.netlify.app/)
> DOCSP-48438-v2.11-backport

- snooty.toml
Fixes broken link in[ v2.13 banner](https://www.mongodb.com/docs/bi-connector/v2.13/).
- [DOCSP-48438](https://jira.mongodb.org/browse/DOCSP-48438)
- [STAGING](https://deploy-preview-460--docs-bi-connector.netlify.app/)
> DOCSP-48438-v2.13-backport

- source/reference/auth-plugin-jdbc.txt
- [DOCSP-46227](https://jira.mongodb.org/browse/DOCSP-46227)
- [STAGING](https://deploy-preview-472--docs-bi-connector.netlify.app/reference/auth-plugin-jdbc/#prerequisites)
> DOCSP-46227: Fix min MySQL Connector J version
